apiVersion: v1
description: A Helm chart to install an openvpn server with duo plugin inside a kubernetes cluster. Based on deprecated stable repo https://github.com/helm/charts/tree/master/stable/openvpn.
name: openvpn-duo
version: 1.0.2
appVersion: 1.0.2
icon: https://forums.openvpn.net/styles/openvpn/theme/images/ovpnlogo.png
keywords:
- openvpn
- vpn
- duo
- tunnel
- network
- service
- connectivity
- encryption
home: https://openvpn.net/index.php/open-source.html
sources:
- https://github.com/jfelten/openvpn-docker
- https://github.com/kubernetes/charts/tree/master/stable/openvpn
- https://github.com/jfelten/helm-charts
